#
# Makefile for the Nios2-specific parts of the memory manager.
#

obj-y	:= init.o ioremap.o pgtable.o tlb.o uaccess.o fault.o
obj-y	+= dma-noncoherent.o
obj-y   += mmu_context.o
obj-y	+= mmdump.o extable.o cacheflush.o
