#
# Makefile for the Linux nios2-specific device drivers.
#

obj-$(CONFIG_PCI)			+= pci/
obj-$(CONFIG_ALTERA_REMOTE_UPDATE)	+= altremote.o
obj-$(CONFIG_PIO_DEVICES)		+= pio.o
obj-$(CONFIG_ALTERA_PIO_GPIO)		+= altera_pio_gpio.o
