#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define TASK_STATE 0 /* offsetof(struct task_struct, state)	#  */
#define TASK_FLAGS 12 /* offsetof(struct task_struct, flags)	#  */
#define TASK_PTRACE 16 /* offsetof(struct task_struct, ptrace)	#  */
#define TASK_BLOCKED 460 /* offsetof(struct task_struct, blocked)	#  */
#define TASK_THREAD 424 /* offsetof(struct task_struct, thread)	#  */
#define TASK_MM 128 /* offsetof(struct task_struct, mm)	#  */
#define TASK_ACTIVE_MM 132 /* offsetof(struct task_struct, active_mm)	#  */
#define STAT_IRQ 64 /* offsetof(struct kernel_stat, irqs)	#  */
#define CPUSTAT_SOFTIRQ_PENDING 0 /* offsetof(irq_cpustat_t, __softirq_pending)	#  */
#define IRQ_HANDLER 0 /* offsetof(struct irq_hand, handler)	#  */
#define IRQ_FLAGS 4 /* offsetof(struct irq_hand, flags)	#  */
#define IRQ_DEV_ID 8 /* offsetof(struct irq_hand, dev_id)	#  */
#define IRQ_DEVNAME 12 /* offsetof(struct irq_hand, devname)	#  */
#define THREAD_KSP 4 /* offsetof(struct thread_struct, ksp)	#  */
#define THREAD_KPSR 8 /* offsetof(struct thread_struct, kpsr)	#  */
#define THREAD_FLAGS 12 /* offsetof(struct thread_struct, flags)	#  */
#define PT_ORIG_R2 60 /* offsetof(struct pt_regs, orig_r2)	#  */
#define PT_ORIG_R7 88 /* offsetof(struct pt_regs, orig_r7)	#  */
#define PT_R1 32 /* offsetof(struct pt_regs, r1)	#  */
#define PT_R2 36 /* offsetof(struct pt_regs, r2)	#  */
#define PT_R3 40 /* offsetof(struct pt_regs, r3)	#  */
#define PT_R4 44 /* offsetof(struct pt_regs, r4)	#  */
#define PT_R5 48 /* offsetof(struct pt_regs, r5)	#  */
#define PT_R6 52 /* offsetof(struct pt_regs, r6)	#  */
#define PT_R7 56 /* offsetof(struct pt_regs, r7)	#  */
#define PT_R8 0 /* offsetof(struct pt_regs, r8)	#  */
#define PT_R9 4 /* offsetof(struct pt_regs, r9)	#  */
#define PT_R10 8 /* offsetof(struct pt_regs, r10)	#  */
#define PT_R11 12 /* offsetof(struct pt_regs, r11)	#  */
#define PT_R12 16 /* offsetof(struct pt_regs, r12)	#  */
#define PT_R13 20 /* offsetof(struct pt_regs, r13)	#  */
#define PT_R14 24 /* offsetof(struct pt_regs, r14)	#  */
#define PT_R15 28 /* offsetof(struct pt_regs, r15)	#  */
#define PT_EA 84 /* offsetof(struct pt_regs, ea)	#  */
#define PT_RA 64 /* offsetof(struct pt_regs, ra)	#  */
#define PT_FP 68 /* offsetof(struct pt_regs, fp)	#  */
#define PT_SP 72 /* offsetof(struct pt_regs, sp)	#  */
#define PT_GP 76 /* offsetof(struct pt_regs, gp)	#  */
#define PT_ESTATUS 80 /* offsetof(struct pt_regs, estatus)	#  */
#define PT_REGS_SIZE 92 /* sizeof(struct pt_regs)	#  */
#define SW_R16 0 /* offsetof(struct switch_stack, r16)	#  */
#define SW_R17 4 /* offsetof(struct switch_stack, r17)	#  */
#define SW_R18 8 /* offsetof(struct switch_stack, r18)	#  */
#define SW_R19 12 /* offsetof(struct switch_stack, r19)	#  */
#define SW_R20 16 /* offsetof(struct switch_stack, r20)	#  */
#define SW_R21 20 /* offsetof(struct switch_stack, r21)	#  */
#define SW_R22 24 /* offsetof(struct switch_stack, r22)	#  */
#define SW_R23 28 /* offsetof(struct switch_stack, r23)	#  */
#define SW_FP 32 /* offsetof(struct switch_stack, fp)	#  */
#define SW_GP 36 /* offsetof(struct switch_stack, gp)	#  */
#define SW_RA 40 /* offsetof(struct switch_stack, ra)	#  */
#define SWITCH_STACK_SIZE 44 /* sizeof(struct switch_stack)	#  */
#define ESTATUS_EU_ASM 2 /* ESTATUS_EU	#  */
#define NIOS2_STATUS_PIE_MSK_ASM 1 /* NIOS2_STATUS_PIE_MSK	#  */
#define NIOS2_STATUS_PIE_OFST_ASM 0 /* NIOS2_STATUS_PIE_OFST	#  */
#define NIOS2_STATUS_U_MSK_ASM 2 /* NIOS2_STATUS_U_MSK	#  */
#define NIOS2_STATUS_U_OFST_ASM 1 /* NIOS2_STATUS_U_OFST	#  */
#define STAT_IRQ 64 /* offsetof(struct kernel_stat, irqs)	#  */
#define TI_TASK 0 /* offsetof(struct thread_info, task)	#  */
#define TI_EXECDOMAIN 4 /* offsetof(struct thread_info, exec_domain)	#  */
#define TI_FLAGS 8 /* offsetof(struct thread_info, flags)	#  */
#define TI_CPU 12 /* offsetof(struct thread_info, cpu)	#  */
#define TI_PREEMPT_COUNT 16 /* offsetof(struct thread_info, preempt_count)	#  */
#define PREEMPT_ACTIVE_ASM 268435456 /* PREEMPT_ACTIVE	#  */
#define THREAD_SIZE_ASM 4096 /* THREAD_SIZE	#  */
#define TIF_SYSCALL_TRACE_ASM 31 /* TIF_SYSCALL_TRACE	#  */
#define TIF_NOTIFY_RESUME_ASM 1 /* TIF_NOTIFY_RESUME	#  */
#define TIF_SIGPENDING_ASM 2 /* TIF_SIGPENDING	#  */
#define TIF_NEED_RESCHED_ASM 3 /* TIF_NEED_RESCHED	#  */
#define TIF_POLLING_NRFLAG_ASM 17 /* TIF_POLLING_NRFLAG	#  */
#define _TIF_SYSCALL_TRACE_ASM -2147483648 /* _TIF_SYSCALL_TRACE	#  */
#define _TIF_NOTIFY_RESUME_ASM 2 /* _TIF_NOTIFY_RESUME	#  */
#define _TIF_SIGPENDING_ASM 4 /* _TIF_SIGPENDING	#  */
#define _TIF_NEED_RESCHED_ASM 8 /* _TIF_NEED_RESCHED	#  */
#define _TIF_POLLING_NRFLAG_ASM 131072 /* _TIF_POLLING_NRFLAG	#  */
#define _TIF_WORK_MASK_ASM 65487 /* _TIF_WORK_MASK	#  */
#define STAT_TLB_FAST_HANDLER 36 /* offsetof(struct tlb_stat, tlb_fast_handler)	#  */
#define LINUX_SDRAM_START 268435456 /* DDR2_TOP_BASE	#  */
#define LINUX_SDRAM_END 402653184 /* DDR2_TOP_BASE+DDR2_TOP_SPAN	#  */
#define NIOS2_ICACHE_SIZE 32768 /* ICACHE_SIZE	#  */
#define NIOS2_ICACHE_LINE_SIZE 32 /* ICACHE_LINE_SIZE	#  */
#define NIOS2_DCACHE_SIZE 32768 /* DCACHE_SIZE	#  */
#define NIOS2_DCACHE_LINE_SIZE 32 /* DCACHE_LINE_SIZE	#  */
#define KERNEL_REGION_BASE_ASM -1073741824 /* KERNEL_REGION_BASE	#  */
#define CPU_EXCEPT_VIRT_ADDRESS_ASM -805306336 /* EXCEPTION_ADDR	#  */
#define CPU_FAST_TLB_MISS_EXCEPTION_VIRT_ADDR_ASM -939527168 /* FAST_TLB_MISS_EXCEPTION_ADDR	#  */

#endif
