#ifndef _CPU_H_
#define _CPU_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 *
 * Created from SOPC Builder system 'NiosII_cycloneII_2c35_full_featured_sopc' in
 * file './NiosII_cycloneII_2c35_full_featured_sopc.sopcinfo'.
 */

/*
 * This file contains macros for module 'cpu' and devices
 * connected to the following masters:
 *   instruction_master
 *   tightly_coupled_instruction_master_0
 *   data_master
 *   tightly_coupled_data_master_0
 *
 * Do not #include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate #defines.
 * Instead, use the system header file which has #defines with unique names.
 */

/*
 * Macros for module 'cpu', class 'altera_nios2'.
 * The macros have no prefix.
 */
#define CPU_IMPLEMENTATION "fast"
#define CPU_FREQ 85000000u
#define ICACHE_LINE_SIZE 32
#define ICACHE_LINE_SIZE_LOG2 5
#define ICACHE_SIZE 4096
#define DCACHE_LINE_SIZE 32
#define DCACHE_LINE_SIZE_LOG2 5
#define DCACHE_SIZE 2048
#define INITDA_SUPPORTED 
#define FLUSHDA_SUPPORTED 
#define HAS_JMPI_INSTRUCTION 
#define MMU_PRESENT 
#define KERNEL_REGION_BASE 0xc0000000
#define IO_REGION_BASE 0xe0000000
#define KERNEL_MMU_REGION_BASE 0x80000000
#define USER_REGION_BASE 0x0
#define PROCESS_ID_NUM_BITS 10
#define TLB_NUM_WAYS 16
#define TLB_NUM_WAYS_LOG2 4
#define TLB_PTR_SZ 7
#define TLB_NUM_ENTRIES 128
#define FAST_TLB_MISS_EXCEPTION_ADDR 0xc8000000
#define EXCEPTION_ADDR 0xc6000020
#define RESET_ADDR 0xc0000000
#define BREAK_ADDR 0xc2120020
#define HAS_DEBUG_STUB 
#define HAS_DEBUG_CORE 1
#define HAS_ILLEGAL_INSTRUCTION_EXCEPTION 
#define HAS_ILLEGAL_MEMORY_ACCESS_EXCEPTION 
#define HAS_EXTRA_EXCEPTION_INFO 
#define CPU_ID_SIZE 1
#define CPU_ID_VALUE 0x0
#define HARDWARE_DIVIDE_PRESENT 0
#define HARDWARE_MULTIPLY_PRESENT 1
#define HARDWARE_MULX_PRESENT 0
#define INST_ADDR_WIDTH 28
#define DATA_ADDR_WIDTH 28

/*
 * Macros for device 'ext_flash', class 'altera_avalon_cfi_flash'
 * The macros are prefixed with 'EXT_FLASH_'.
 * The prefix is the slave descriptor.
 */
#define EXT_FLASH_COMPONENT_TYPE altera_avalon_cfi_flash
#define EXT_FLASH_COMPONENT_NAME ext_flash
#define EXT_FLASH_BASE 0x0
#define EXT_FLASH_SPAN 16777216u
#define EXT_FLASH_SETUP_VALUE 45
#define EXT_FLASH_WAIT_VALUE 160
#define EXT_FLASH_HOLD_VALUE 35
#define EXT_FLASH_TIMING_UNITS "ns"
#define EXT_FLASH_SIZE 16777216u

/*
 * Macros for device 'pll', class 'altera_avalon_pll'
 * The macros are prefixed with 'PLL_'.
 * The prefix is the slave descriptor.
 */
#define PLL_COMPONENT_TYPE altera_avalon_pll
#define PLL_COMPONENT_NAME pll
#define PLL_BASE 0x1000020
#define PLL_SPAN 32u
#define PLL_ARESET "None"
#define PLL_PFDENA "None"
#define PLL_LOCKED "None"
#define PLL_PLLENA "None"
#define PLL_SCANCLK "None"
#define PLL_SCANDATA "None"
#define PLL_SCANREAD "None"
#define PLL_SCANWRITE "None"
#define PLL_SCANCLKENA "None"
#define PLL_SCANACLR "None"
#define PLL_SCANDATAOUT "None"
#define PLL_SCANDONE "None"
#define PLL_CONFIGUPDATE "None"
#define PLL_PHASECOUNTERSELECT "None"
#define PLL_PHASEDONE "None"
#define PLL_PHASEUPDOWN "None"
#define PLL_PHASESTEP "None"

/*
 * Macros for device 'pllsysx2', class 'altera_avalon_pll'
 * The macros are prefixed with 'PLLSYSX2_'.
 * The prefix is the slave descriptor.
 */
#define PLLSYSX2_COMPONENT_TYPE altera_avalon_pll
#define PLLSYSX2_COMPONENT_NAME pllsysx2
#define PLLSYSX2_BASE 0x1000040
#define PLLSYSX2_SPAN 32u
#define PLLSYSX2_ARESET "None"
#define PLLSYSX2_PFDENA "None"
#define PLLSYSX2_LOCKED "None"
#define PLLSYSX2_PLLENA "None"
#define PLLSYSX2_SCANCLK "None"
#define PLLSYSX2_SCANDATA "None"
#define PLLSYSX2_SCANREAD "None"
#define PLLSYSX2_SCANWRITE "None"
#define PLLSYSX2_SCANCLKENA "None"
#define PLLSYSX2_SCANACLR "None"
#define PLLSYSX2_SCANDATAOUT "None"
#define PLLSYSX2_SCANDONE "None"
#define PLLSYSX2_CONFIGUPDATE "None"
#define PLLSYSX2_PHASECOUNTERSELECT "None"
#define PLLSYSX2_PHASEDONE "None"
#define PLLSYSX2_PHASEUPDOWN "None"
#define PLLSYSX2_PHASESTEP "None"

/*
 * Macros for device 'ext_ssram', class 'altera_avalon_cy7c1380_ssram'
 * The macros are prefixed with 'EXT_SSRAM_'.
 * The prefix is the slave descriptor.
 */
#define EXT_SSRAM_COMPONENT_TYPE altera_avalon_cy7c1380_ssram
#define EXT_SSRAM_COMPONENT_NAME ext_ssram
#define EXT_SSRAM_BASE 0x1400000
#define EXT_SSRAM_SPAN 2097152u
#define EXT_SSRAM_SRAM_MEMORY_SIZE 2
#define EXT_SSRAM_SRAM_MEMORY_UNITS 1048576
#define EXT_SSRAM_SSRAM_DATA_WIDTH 32
#define EXT_SSRAM_SSRAM_READ_LATENCY 2

/*
 * Macros for device 'lan91c111', class 'altera_avalon_lan91c111'
 * The macros are prefixed with 'LAN91C111_'.
 * The prefix is the slave descriptor.
 */
#define LAN91C111_COMPONENT_TYPE altera_avalon_lan91c111
#define LAN91C111_COMPONENT_NAME lan91c111
#define LAN91C111_BASE 0x2110000
#define LAN91C111_SPAN 65536u
#define LAN91C111_IRQ 6
#define LAN91C111_IS_ETHERNET_MAC 1
#define LAN91C111_LAN91C111_REGISTERS_OFFSET 768
#define LAN91C111_LAN91C111_DATA_BUS_WIDTH 32

/*
 * Macros for device 'sys_clk_timer', class 'altera_avalon_timer'
 * The macros are prefixed with 'SYS_CLK_TIMER_'.
 * The prefix is the slave descriptor.
 */
#define SYS_CLK_TIMER_COMPONENT_TYPE altera_avalon_timer
#define SYS_CLK_TIMER_COMPONENT_NAME sys_clk_timer
#define SYS_CLK_TIMER_BASE 0x2120800
#define SYS_CLK_TIMER_SPAN 32u
#define SYS_CLK_TIMER_IRQ 0
#define SYS_CLK_TIMER_ALWAYS_RUN 0
#define SYS_CLK_TIMER_FIXED_PERIOD 0
#define SYS_CLK_TIMER_SNAPSHOT 1
#define SYS_CLK_TIMER_PERIOD 10.0
#define SYS_CLK_TIMER_PERIOD_UNITS "ms"
#define SYS_CLK_TIMER_RESET_OUTPUT 0
#define SYS_CLK_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define SYS_CLK_TIMER_FREQ 85000000u
#define SYS_CLK_TIMER_LOAD_VALUE 849999ULL
#define SYS_CLK_TIMER_COUNTER_SIZE 32
#define SYS_CLK_TIMER_MULT 0.0010
#define SYS_CLK_TIMER_TICKS_PER_SEC 100u

/*
 * Macros for device 'high_res_timer', class 'altera_avalon_timer'
 * The macros are prefixed with 'HIGH_RES_TIMER_'.
 * The prefix is the slave descriptor.
 */
#define HIGH_RES_TIMER_COMPONENT_TYPE altera_avalon_timer
#define HIGH_RES_TIMER_COMPONENT_NAME high_res_timer
#define HIGH_RES_TIMER_BASE 0x2120820
#define HIGH_RES_TIMER_SPAN 32u
#define HIGH_RES_TIMER_IRQ 3
#define HIGH_RES_TIMER_ALWAYS_RUN 0
#define HIGH_RES_TIMER_FIXED_PERIOD 0
#define HIGH_RES_TIMER_SNAPSHOT 1
#define HIGH_RES_TIMER_PERIOD 10.0
#define HIGH_RES_TIMER_PERIOD_UNITS "us"
#define HIGH_RES_TIMER_RESET_OUTPUT 0
#define HIGH_RES_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define HIGH_RES_TIMER_FREQ 85000000u
#define HIGH_RES_TIMER_LOAD_VALUE 849ULL
#define HIGH_RES_TIMER_COUNTER_SIZE 32
#define HIGH_RES_TIMER_MULT 1.0E-6
#define HIGH_RES_TIMER_TICKS_PER_SEC 100000u

/*
 * Macros for device 'uart1', class 'altera_avalon_uart'
 * The macros are prefixed with 'UART1_'.
 * The prefix is the slave descriptor.
 */
#define UART1_COMPONENT_TYPE altera_avalon_uart
#define UART1_COMPONENT_NAME uart1
#define UART1_BASE 0x2120840
#define UART1_SPAN 32u
#define UART1_IRQ 4
#define UART1_BAUD 115200
#define UART1_DATA_BITS 8
#define UART1_FIXED_BAUD 1
#define UART1_PARITY 'N'
#define UART1_STOP_BITS 1
#define UART1_SYNC_REG_DEPTH 2
#define UART1_USE_CTS_RTS 0
#define UART1_USE_EOP_REGISTER 0
#define UART1_SIM_TRUE_BAUD 0
#define UART1_SIM_CHAR_STREAM ""
#define UART1_FREQ 85000000u

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x2120860
#define BUTTON_PIO_SPAN 16u
#define BUTTON_PIO_IRQ 2
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 1
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0xf
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_CAPTURE 1
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_DATA_WIDTH 4
#define BUTTON_PIO_RESET_VALUE 0x0
#define BUTTON_PIO_EDGE_TYPE "ANY"
#define BUTTON_PIO_IRQ_TYPE "EDGE"
#define BUTTON_PIO_FREQ 85000000u

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x2120870
#define LED_PIO_SPAN 16u
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0x0
#define LED_PIO_HAS_TRI 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_IN 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_DATA_WIDTH 8
#define LED_PIO_RESET_VALUE 0x0
#define LED_PIO_EDGE_TYPE "NONE"
#define LED_PIO_IRQ_TYPE "NONE"
#define LED_PIO_FREQ 85000000u

/*
 * Macros for device 'lcd_display', class 'altera_avalon_lcd_16207'
 * The macros are prefixed with 'LCD_DISPLAY_'.
 * The prefix is the slave descriptor.
 */
#define LCD_DISPLAY_COMPONENT_TYPE altera_avalon_lcd_16207
#define LCD_DISPLAY_COMPONENT_NAME lcd_display
#define LCD_DISPLAY_BASE 0x2120880
#define LCD_DISPLAY_SPAN 16u

/*
 * Macros for device 'seven_seg_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'SEVEN_SEG_PIO_'.
 * The prefix is the slave descriptor.
 */
#define SEVEN_SEG_PIO_COMPONENT_TYPE altera_avalon_pio
#define SEVEN_SEG_PIO_COMPONENT_NAME seven_seg_pio
#define SEVEN_SEG_PIO_BASE 0x2120890
#define SEVEN_SEG_PIO_SPAN 16u
#define SEVEN_SEG_PIO_DO_TEST_BENCH_WIRING 0
#define SEVEN_SEG_PIO_DRIVEN_SIM_VALUE 0x0
#define SEVEN_SEG_PIO_HAS_TRI 0
#define SEVEN_SEG_PIO_HAS_OUT 1
#define SEVEN_SEG_PIO_HAS_IN 0
#define SEVEN_SEG_PIO_CAPTURE 0
#define SEVEN_SEG_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SEVEN_SEG_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEVEN_SEG_PIO_DATA_WIDTH 16
#define SEVEN_SEG_PIO_RESET_VALUE 0x0
#define SEVEN_SEG_PIO_EDGE_TYPE "NONE"
#define SEVEN_SEG_PIO_IRQ_TYPE "NONE"
#define SEVEN_SEG_PIO_FREQ 85000000u

/*
 * Macros for device 'reconfig_request_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'RECONFIG_REQUEST_PIO_'.
 * The prefix is the slave descriptor.
 */
#define RECONFIG_REQUEST_PIO_COMPONENT_TYPE altera_avalon_pio
#define RECONFIG_REQUEST_PIO_COMPONENT_NAME reconfig_request_pio
#define RECONFIG_REQUEST_PIO_BASE 0x21208a0
#define RECONFIG_REQUEST_PIO_SPAN 16u
#define RECONFIG_REQUEST_PIO_DO_TEST_BENCH_WIRING 0
#define RECONFIG_REQUEST_PIO_DRIVEN_SIM_VALUE 0x0
#define RECONFIG_REQUEST_PIO_HAS_TRI 1
#define RECONFIG_REQUEST_PIO_HAS_OUT 0
#define RECONFIG_REQUEST_PIO_HAS_IN 0
#define RECONFIG_REQUEST_PIO_CAPTURE 0
#define RECONFIG_REQUEST_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define RECONFIG_REQUEST_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RECONFIG_REQUEST_PIO_DATA_WIDTH 1
#define RECONFIG_REQUEST_PIO_RESET_VALUE 0x0
#define RECONFIG_REQUEST_PIO_EDGE_TYPE "NONE"
#define RECONFIG_REQUEST_PIO_IRQ_TYPE "NONE"
#define RECONFIG_REQUEST_PIO_FREQ 85000000u

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x21208b0
#define JTAG_UART_SPAN 8u
#define JTAG_UART_IRQ 1
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8
#define JTAG_UART_READ_THRESHOLD 8

/*
 * Macros for device 'sysid', class 'altera_avalon_sysid'
 * The macros are prefixed with 'SYSID_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_COMPONENT_TYPE altera_avalon_sysid
#define SYSID_COMPONENT_NAME sysid
#define SYSID_BASE 0x21208b8
#define SYSID_SPAN 8u
#define SYSID_ID 415554621u
#define SYSID_TIMESTAMP 1236504349u

/*
 * Macros for device 'performance_counter', class 'altera_avalon_performance_counter'
 * The macros are prefixed with 'PERFORMANCE_COUNTER_'.
 * The prefix is the slave descriptor.
 */
#define PERFORMANCE_COUNTER_COMPONENT_TYPE altera_avalon_performance_counter
#define PERFORMANCE_COUNTER_COMPONENT_NAME performance_counter
#define PERFORMANCE_COUNTER_BASE 0x2120900
#define PERFORMANCE_COUNTER_SPAN 64u
#define PERFORMANCE_COUNTER_HOW_MANY_SECTIONS 3

/*
 * Macros for device 'dma', class 'altera_avalon_dma'
 * The macros are prefixed with 'DMA_'.
 * The prefix is the slave descriptor.
 */
#define DMA_COMPONENT_TYPE altera_avalon_dma
#define DMA_COMPONENT_NAME dma
#define DMA_BASE 0x2120a00
#define DMA_SPAN 32u
#define DMA_IRQ 7
#define DMA_LENGTHWIDTH 13
#define DMA_ALLOW_BYTE_TRANSACTIONS 1
#define DMA_ALLOW_HW_TRANSACTIONS 1
#define DMA_ALLOW_WORD_TRANSACTIONS 1
#define DMA_ALLOW_DOUBLEWORD_TRANSACTIONS 1
#define DMA_ALLOW_QUADWORD_TRANSACTIONS 1
#define DMA_MAX_BURST_SIZE 128

/*
 * Macros for device 'ext_flash', class 'altera_avalon_cfi_flash'
 * Path to the device is from the master group 'dma_read_master'.
 * The macros are prefixed with 'DMA_READ_MASTER_EXT_FLASH_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_READ_MASTER_EXT_FLASH_COMPONENT_TYPE altera_avalon_cfi_flash
#define DMA_READ_MASTER_EXT_FLASH_COMPONENT_NAME ext_flash
#define DMA_READ_MASTER_EXT_FLASH_BASE 0x0
#define DMA_READ_MASTER_EXT_FLASH_SPAN 16777216u
#define DMA_READ_MASTER_EXT_FLASH_SETUP_VALUE 45
#define DMA_READ_MASTER_EXT_FLASH_WAIT_VALUE 160
#define DMA_READ_MASTER_EXT_FLASH_HOLD_VALUE 35
#define DMA_READ_MASTER_EXT_FLASH_TIMING_UNITS "ns"
#define DMA_READ_MASTER_EXT_FLASH_SIZE 16777216u

/*
 * Macros for device 'ext_ssram', class 'altera_avalon_cy7c1380_ssram'
 * Path to the device is from the master group 'dma_read_master'.
 * The macros are prefixed with 'DMA_READ_MASTER_EXT_SSRAM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_READ_MASTER_EXT_SSRAM_COMPONENT_TYPE altera_avalon_cy7c1380_ssram
#define DMA_READ_MASTER_EXT_SSRAM_COMPONENT_NAME ext_ssram
#define DMA_READ_MASTER_EXT_SSRAM_BASE 0x1400000
#define DMA_READ_MASTER_EXT_SSRAM_SPAN 2097152u
#define DMA_READ_MASTER_EXT_SSRAM_SRAM_MEMORY_SIZE 2
#define DMA_READ_MASTER_EXT_SSRAM_SRAM_MEMORY_UNITS 1048576
#define DMA_READ_MASTER_EXT_SSRAM_SSRAM_DATA_WIDTH 32
#define DMA_READ_MASTER_EXT_SSRAM_SSRAM_READ_LATENCY 2

/*
 * Macros for device 'lan91c111', class 'altera_avalon_lan91c111'
 * Path to the device is from the master group 'dma_read_master'.
 * The macros are prefixed with 'DMA_READ_MASTER_LAN91C111_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_READ_MASTER_LAN91C111_COMPONENT_TYPE altera_avalon_lan91c111
#define DMA_READ_MASTER_LAN91C111_COMPONENT_NAME lan91c111
#define DMA_READ_MASTER_LAN91C111_BASE 0x2110000
#define DMA_READ_MASTER_LAN91C111_SPAN 65536u
#define DMA_READ_MASTER_LAN91C111_IS_ETHERNET_MAC 1
#define DMA_READ_MASTER_LAN91C111_LAN91C111_REGISTERS_OFFSET 768
#define DMA_READ_MASTER_LAN91C111_LAN91C111_DATA_BUS_WIDTH 32

/*
 * Macros for device 'ddr_sdram_0', class 'ddr_sdram_component_classic'
 * Path to the device is from the master group 'dma_read_master'.
 * The macros are prefixed with 'DMA_READ_MASTER_DDR_SDRAM_0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_READ_MASTER_DDR_SDRAM_0_COMPONENT_TYPE ddr_sdram_component_classic
#define DMA_READ_MASTER_DDR_SDRAM_0_COMPONENT_NAME ddr_sdram_0
#define DMA_READ_MASTER_DDR_SDRAM_0_BASE 0x6000000
#define DMA_READ_MASTER_DDR_SDRAM_0_SPAN 33554432u

/*
 * Macros for device 'tightly_coupled_data_memory', class 'altera_avalon_onchip_memory2'
 * Path to the device is from the master group 'dma_read_master'.
 * The macros are prefixed with 'DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_COMPONENT_TYPE altera_avalon_onchip_memory2
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_COMPONENT_NAME tightly_coupled_data_memory
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_BASE 0x8002000
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_SPAN 8192u
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_INIT_CONTENTS_FILE "tightly_coupled_data_memory"
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_GUI_RAM_BLOCK_TYPE "Automatic"
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_WRITABLE 1
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_DUAL_PORT 1
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_SIZE_VALUE 8192u
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_SIZE_MULTIPLE 1
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_CONTENTS_INFO ""
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_RAM_BLOCK_TYPE "Auto"
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_INIT_MEM_CONTENT 1
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_INSTANCE_ID "NONE"
#define DMA_READ_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"

/*
 * Macros for device 'ext_flash', class 'altera_avalon_cfi_flash'
 * Path to the device is from the master group 'dma_write_master'.
 * The macros are prefixed with 'DMA_WRITE_MASTER_EXT_FLASH_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_WRITE_MASTER_EXT_FLASH_COMPONENT_TYPE altera_avalon_cfi_flash
#define DMA_WRITE_MASTER_EXT_FLASH_COMPONENT_NAME ext_flash
#define DMA_WRITE_MASTER_EXT_FLASH_BASE 0x0
#define DMA_WRITE_MASTER_EXT_FLASH_SPAN 16777216u
#define DMA_WRITE_MASTER_EXT_FLASH_SETUP_VALUE 45
#define DMA_WRITE_MASTER_EXT_FLASH_WAIT_VALUE 160
#define DMA_WRITE_MASTER_EXT_FLASH_HOLD_VALUE 35
#define DMA_WRITE_MASTER_EXT_FLASH_TIMING_UNITS "ns"
#define DMA_WRITE_MASTER_EXT_FLASH_SIZE 16777216u

/*
 * Macros for device 'ext_ssram', class 'altera_avalon_cy7c1380_ssram'
 * Path to the device is from the master group 'dma_write_master'.
 * The macros are prefixed with 'DMA_WRITE_MASTER_EXT_SSRAM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_WRITE_MASTER_EXT_SSRAM_COMPONENT_TYPE altera_avalon_cy7c1380_ssram
#define DMA_WRITE_MASTER_EXT_SSRAM_COMPONENT_NAME ext_ssram
#define DMA_WRITE_MASTER_EXT_SSRAM_BASE 0x1400000
#define DMA_WRITE_MASTER_EXT_SSRAM_SPAN 2097152u
#define DMA_WRITE_MASTER_EXT_SSRAM_SRAM_MEMORY_SIZE 2
#define DMA_WRITE_MASTER_EXT_SSRAM_SRAM_MEMORY_UNITS 1048576
#define DMA_WRITE_MASTER_EXT_SSRAM_SSRAM_DATA_WIDTH 32
#define DMA_WRITE_MASTER_EXT_SSRAM_SSRAM_READ_LATENCY 2

/*
 * Macros for device 'lan91c111', class 'altera_avalon_lan91c111'
 * Path to the device is from the master group 'dma_write_master'.
 * The macros are prefixed with 'DMA_WRITE_MASTER_LAN91C111_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_WRITE_MASTER_LAN91C111_COMPONENT_TYPE altera_avalon_lan91c111
#define DMA_WRITE_MASTER_LAN91C111_COMPONENT_NAME lan91c111
#define DMA_WRITE_MASTER_LAN91C111_BASE 0x2110000
#define DMA_WRITE_MASTER_LAN91C111_SPAN 65536u
#define DMA_WRITE_MASTER_LAN91C111_IS_ETHERNET_MAC 1
#define DMA_WRITE_MASTER_LAN91C111_LAN91C111_REGISTERS_OFFSET 768
#define DMA_WRITE_MASTER_LAN91C111_LAN91C111_DATA_BUS_WIDTH 32

/*
 * Macros for device 'ddr_sdram_0', class 'ddr_sdram_component_classic'
 * Path to the device is from the master group 'dma_write_master'.
 * The macros are prefixed with 'DMA_WRITE_MASTER_DDR_SDRAM_0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_WRITE_MASTER_DDR_SDRAM_0_COMPONENT_TYPE ddr_sdram_component_classic
#define DMA_WRITE_MASTER_DDR_SDRAM_0_COMPONENT_NAME ddr_sdram_0
#define DMA_WRITE_MASTER_DDR_SDRAM_0_BASE 0x6000000
#define DMA_WRITE_MASTER_DDR_SDRAM_0_SPAN 33554432u

/*
 * Macros for device 'tightly_coupled_data_memory', class 'altera_avalon_onchip_memory2'
 * Path to the device is from the master group 'dma_write_master'.
 * The macros are prefixed with 'DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_COMPONENT_TYPE altera_avalon_onchip_memory2
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_COMPONENT_NAME tightly_coupled_data_memory
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_BASE 0x8002000
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_SPAN 8192u
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_INIT_CONTENTS_FILE "tightly_coupled_data_memory"
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_GUI_RAM_BLOCK_TYPE "Automatic"
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_WRITABLE 1
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_DUAL_PORT 1
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_SIZE_VALUE 8192u
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_SIZE_MULTIPLE 1
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_CONTENTS_INFO ""
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_RAM_BLOCK_TYPE "Auto"
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_INIT_MEM_CONTENT 1
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_INSTANCE_ID "NONE"
#define DMA_WRITE_MASTER_TIGHTLY_COUPLED_DATA_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"

/*
 * Macros for device 'epcs_controller', class 'altera_avalon_epcs_flash_controller'
 * The macros are prefixed with 'EPCS_CONTROLLER_'.
 * The prefix is the slave descriptor.
 */
#define EPCS_CONTROLLER_COMPONENT_TYPE altera_avalon_epcs_flash_controller
#define EPCS_CONTROLLER_COMPONENT_NAME epcs_controller
#define EPCS_CONTROLLER_BASE 0x3200000
#define EPCS_CONTROLLER_SPAN 2048u
#define EPCS_CONTROLLER_IRQ 5
#define EPCS_CONTROLLER_REGISTER_OFFSET 512

/*
 * Macros for device 'ddr_sdram_0', class 'ddr_sdram_component_classic'
 * The macros are prefixed with 'DDR_SDRAM_0_'.
 * The prefix is the slave descriptor.
 */
#define DDR_SDRAM_0_COMPONENT_TYPE ddr_sdram_component_classic
#define DDR_SDRAM_0_COMPONENT_NAME ddr_sdram_0
#define DDR_SDRAM_0_BASE 0x6000000
#define DDR_SDRAM_0_SPAN 33554432u

/*
 * Macros for device 'tightly_coupled_instruction_memory', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'TIGHTLY_COUPLED_INSTRUCTION_MEMORY_'.
 * The prefix is the slave descriptor.
 */
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_COMPONENT_TYPE altera_avalon_onchip_memory2
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_COMPONENT_NAME tightly_coupled_instruction_memory
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_BASE 0x8000000
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_SPAN 4096u
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_INIT_CONTENTS_FILE "tightly_coupled_instruction_memory"
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_GUI_RAM_BLOCK_TYPE "Automatic"
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_WRITABLE 1
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_DUAL_PORT 1
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_SIZE_VALUE 4096u
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_SIZE_MULTIPLE 1
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_CONTENTS_INFO ""
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_RAM_BLOCK_TYPE "Auto"
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_INIT_MEM_CONTENT 1
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_INSTANCE_ID "NONE"
#define TIGHTLY_COUPLED_INSTRUCTION_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"

/*
 * Macros for device 'tightly_coupled_data_memory', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'TIGHTLY_COUPLED_DATA_MEMORY_'.
 * The prefix is the slave descriptor.
 */
#define TIGHTLY_COUPLED_DATA_MEMORY_COMPONENT_TYPE altera_avalon_onchip_memory2
#define TIGHTLY_COUPLED_DATA_MEMORY_COMPONENT_NAME tightly_coupled_data_memory
#define TIGHTLY_COUPLED_DATA_MEMORY_BASE 0x8002000
#define TIGHTLY_COUPLED_DATA_MEMORY_SPAN 8192u
#define TIGHTLY_COUPLED_DATA_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define TIGHTLY_COUPLED_DATA_MEMORY_INIT_CONTENTS_FILE "tightly_coupled_data_memory"
#define TIGHTLY_COUPLED_DATA_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define TIGHTLY_COUPLED_DATA_MEMORY_GUI_RAM_BLOCK_TYPE "Automatic"
#define TIGHTLY_COUPLED_DATA_MEMORY_WRITABLE 1
#define TIGHTLY_COUPLED_DATA_MEMORY_DUAL_PORT 1
#define TIGHTLY_COUPLED_DATA_MEMORY_SIZE_VALUE 8192u
#define TIGHTLY_COUPLED_DATA_MEMORY_SIZE_MULTIPLE 1
#define TIGHTLY_COUPLED_DATA_MEMORY_CONTENTS_INFO ""
#define TIGHTLY_COUPLED_DATA_MEMORY_RAM_BLOCK_TYPE "Auto"
#define TIGHTLY_COUPLED_DATA_MEMORY_INIT_MEM_CONTENT 1
#define TIGHTLY_COUPLED_DATA_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define TIGHTLY_COUPLED_DATA_MEMORY_INSTANCE_ID "NONE"
#define TIGHTLY_COUPLED_DATA_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"


#endif /* _CPU_H_ */
